
nrm-rabbitmq:
  image: rabbitmq:management
  container_name: nrm-rabbitmq5000
  ##hostname: nrmrabbitmqhost
  #networks:
  #  nrmmq:
  #    aliases:
  #      - nrmrabbitmqhost
  ports:
    - "5672:5672"
    - "15672:15672"
  restart: always
  volumes:
    - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    - ./definitions.json:/etc/rabbitmq/definitions.json
    #- ./data:/var/lib/rabbitmq:rw
    #- /etc/hosts:/etc/hosts
    #- /etc/localtime:/etc/localtime:ro
  #environment:
    #- TZ=Asia/Taipei
#networks:
#  nrmmq:
    ##aliases:
      ##- nrmrabbitmqhost
